// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbT5ql2WUj5PcDWElLLxoQ-uNGnNlSeQE',
    appId: '1:810429791548:web:4041bb8fd3ceb1f966f239',
    messagingSenderId: '810429791548',
    projectId: 'wealth-calculator-d7d63',
    authDomain: 'wealth-calculator-d7d63.firebaseapp.com',
    storageBucket: 'wealth-calculator-d7d63.firebasestorage.app',
    measurementId: 'G-YZH27RVKLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArRtVKzj--lX9CFvJUnMzm31kAQmEXGF4',
    appId: '1:810429791548:android:ff87f6e6cead2ffd66f239',
    messagingSenderId: '810429791548',
    projectId: 'wealth-calculator-d7d63',
    storageBucket: 'wealth-calculator-d7d63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwstSrkqoXvvLMX17MPS_yvH4Z9TJp6Ik',
    appId: '1:810429791548:ios:a4e59dc656b0811466f239',
    messagingSenderId: '810429791548',
    projectId: 'wealth-calculator-d7d63',
    storageBucket: 'wealth-calculator-d7d63.firebasestorage.app',
    iosBundleId: 'com.example.wealthCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwstSrkqoXvvLMX17MPS_yvH4Z9TJp6Ik',
    appId: '1:810429791548:ios:a4e59dc656b0811466f239',
    messagingSenderId: '810429791548',
    projectId: 'wealth-calculator-d7d63',
    storageBucket: 'wealth-calculator-d7d63.firebasestorage.app',
    iosBundleId: 'com.example.wealthCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbT5ql2WUj5PcDWElLLxoQ-uNGnNlSeQE',
    appId: '1:810429791548:web:7f4854a64d7b9f3b66f239',
    messagingSenderId: '810429791548',
    projectId: 'wealth-calculator-d7d63',
    authDomain: 'wealth-calculator-d7d63.firebaseapp.com',
    storageBucket: 'wealth-calculator-d7d63.firebasestorage.app',
    measurementId: 'G-BR418JW6SB',
  );
}
